apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-app
  template:
    metadata:
      labels:
        app: try-app
    spec:
      containers:
      - name: try-app
        image: try-app:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: try-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    app: try-app
