version: '3.8'
services:
  flask-app:
    container_name: flask-app
    image: flask-app:latest
    ports:
     - "${PORT}:${PORT}"
     - "${METRICS_PORT}:${METRICS_PORT}"
    volumes:
     - .:/code
    environment:
      - PORT=${PORT}
      - METRICS_PORT=${METRICS_PORT}