version: '3.8'

networks:
  main:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - main

  ml_server:
    build: .
    container_name: ml_server
    ports:
      - "5000:5000"  
    depends_on:
      - redis
    networks:
      - main
