version: '3.8'
services:
  resnet18-flask-app:
    container_name: resnet18-flask-app
    image: resnet18-flask-app:latest
    ports:
     - "${PORT}:${PORT}"
     - "${METRICS_PORT}:${METRICS_PORT}"
    volumes:
     - .:/code
    depends_on:
     - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis