apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-configmap
  namespace: default
data:
  PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090" 
  MOVING_AVERAGE_DURATION: "1m"
  COOLDOWN_PERIOD: "30"
  DEPLOYMENT_NAME: "flask-app"
  NAMESPACE: "default"
  LATENCY_THRESHOLD_UP: "0.20"
  LATENCY_THRESHOLD_DOWN: "0.1"
  COUNT_THRESHOLD: "20"
  MAX_REPLICAS: "8"
  MIN_REPLICAS: "1"
  MAX_FAILURES: "3"
